# 新增/更改别名请复制此文件到此目录并重命名为SimpleTeamArr.yaml。【注:自己添加别名请注意格式】
{
    雷九: { alias: [ 雷九万班 ], chars: [ 雷电将军,九条裟罗,枫原万叶,班尼特 ] },
    雷国: { alias: [ 雷神国家队 ], chars: [  雷电将军,班尼特, 香菱, 行秋 ] },
    雷万香班: { alias: [], chars: [ 雷电将军, 万叶, 香菱, 班尼特 ] },
    雷优钟班: { alias: [], chars: [ 雷电将军, 优菈, 钟离, 班尼特 ] },
    魈琴钟阿: [ 魈, 琴, 钟离, 阿贝多 ],
    魈钟班砂: [ 魈, 钟离, 班尼特, 砂糖],
    魈钟班法: [ 魈, 钟离, 班尼特, 珐露珊 ],
    万达国际: [ 枫原万叶, 达达利亚, 班尼特, 香菱 ],
    一斗纯岩: [ 荒泷一斗, 五郎, 钟离, 阿贝多 ],
    魔王武装: [ 达达利亚, 行秋, 北斗, 菲谢尔 ],
    胡行夜钟: { alias: [ 胡夜行钟, ], chars: [ 胡桃, 行秋, 夜兰, 钟离 ] },
    胡行钟阿: { alias: [ 胡行阿钟 ], chars: [ 胡桃, 行秋, 钟离, 阿贝多 ] },
    胡行钟砂: [ 胡桃, 行秋, 钟离, 砂糖 ],
    胡行钟香: [ 胡桃, 行秋, 钟离, 香菱 ],
    胡桃种门: { alias: [ 胡草行久,草行久胡], chars: [ 草神, 行秋, 久歧忍, 胡桃 ] },
    雷达国际: [ 雷电将军, 达达利亚, 班尼特, 香菱 ],
    心海武装: [ 珊瑚宫心海, 行秋, 枫原万叶, 八重神子 ],
    神鹤万心: { alias: [ 神鹤 ], chars: [ 神里绫华, 申鹤, 万叶, 心海 ] },
    神甘万心: { alias: [ 神甘 ], chars: [ 神里绫华, 甘雨, 万叶, 心海 ] },
    神罗万心: { alias: [ 神罗 ], chars: [ 神里绫华, 罗莎莉亚, 万叶, 心海 ] },
    神行万猫: [ 神里绫华, 行秋, 万叶, 迪奥娜 ],
    神行温猫: [ 神里绫华, 行秋, 温迪, 迪奥娜 ],
    神莫万猫: { alias: [ 神猫万莫,神莫万娜,神娜万莫 ], chars: [ 神里绫华, 莫娜, 万叶, 迪奥娜 ] },
    神莫温娜: { alias: [ 神娜温莫,神莫温猫,神猫温莫 ], chars: [ 神里绫华, 莫娜, 温迪, 迪奥娜 ] },
    神莫砂猫: { alias: [ 神猫砂莫,神莫砂娜,神娜砂莫 ], chars: [ 神里绫华, 莫娜, 砂糖, 迪奥娜 ] },
    莫甘温娜: [ 莫娜, 甘雨, 温迪, 迪奥娜 ],
    万雷国队: [ 万叶, 班尼特, 雷电将军, 香菱 ],
    融甘: [ 甘雨, 香菱, 班尼特, 钟离 ],
    可莉三火: [ 可莉, 香菱, 班尼特, 万叶 ],
    凌人国际: [ 神里绫人, 枫原万叶, 香菱, 班尼特 ],
    草国: { alias: [ 草行久,草神国家队,草行久菲 ], chars: [ 草神, 行秋, 久岐忍, 菲谢尔 ] },
    夜宵钟云: { alias: [ 宵夜钟云], chars: [ 夜兰, 宵宫, 钟离, 云堇 ] },
    烟花武装: [ 宵宫, 行秋, 北斗, 班尼特 ],
    宵行云班: [ 宵宫, 行秋, 云堇, 班尼特 ],
    妮绽放: { alias: [ 妮露绽放 ], chars: [ 妮露, 心海, 草神, 瑶瑶 ] },
    玉皇妲帝: { alias: [ 刻钟皇草 ], chars: [ 刻晴, 皇女, 草神, 钟离 ] },
    砂糖武装: [ 砂糖, 行秋, 北斗, 菲谢尔 ],
    砂糖国家队: [ 砂糖, 香菱, 行秋, 班尼特 ]
  }